startnode:
	python3 commands.py --start_node $(ENV) $(CurrentNode) $(User) $(Password) $(Cookie) $(Node2) $(Node3)
stopnode:
	python3 commands.py --stop_node
watchnode:
	python3 commands.py --watch_node
bashnode:
	python3 commands.py --bash_node
help:
	python3 commands.py -h